### ISSUE TITLE
Keychron V1 Encoder ISO

### ISSUE THREAD

**Issue by Dafiilicous** [SRGBmods/qmk-plugins#3]
Would it be possible to add a Keychron v1 encoder ISO firmware with signalrgb compatability in iso?

Thx in advance

**Comment by naitoshedo** [comment]
That firmware exists: https://github.com/SRGBmods/QMK-Binaries/tree/main/QMK%2BVIA-Firmware/0.24.4/K-O
![image](https://github.com/SRGBmods/qmk-plugins/assets/5493213/016ff58b-0ef1-41f8-869a-df3a84add767)
